language: node_js
node_js:
  - "0.12"

sudo: false

env:
  - FIREFOX_BIN=`which firefox`
  - PHANTOMJS_BIN=`which phantomjs`

cache:
  directories:
    - node_modules
    - typings

before_install:
  - "node --version"
  - "npm --version"
  - "nvm --version"
  - "npm config set spin false"
  - "phantomjs --version"
  - "firefox --version"
  - "echo $FIREFOX_BIN"
  - "echo $PHANTOMJS_BIN"

install:
  - "npm install"

script:
  - npm test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start